// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/edwintantawi/taskit/internal/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *TaskUsecase) Create(ctx context.Context, payload *dto.CreateTaskIn) (dto.CreateTaskOut, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.CreateTaskOut
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateTaskIn) dto.CreateTaskOut); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.CreateTaskOut)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateTaskIn) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, payload
func (_m *TaskUsecase) GetAll(ctx context.Context, payload *dto.GetAllTaskIn) ([]dto.GetAllTaskOut, error) {
	ret := _m.Called(ctx, payload)

	var r0 []dto.GetAllTaskOut
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetAllTaskIn) []dto.GetAllTaskOut); ok {
		r0 = rf(ctx, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.GetAllTaskOut)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetAllTaskIn) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, payload
func (_m *TaskUsecase) GetByID(ctx context.Context, payload *dto.GetTaskByIDIn) (dto.GetTaskByIDOut, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.GetTaskByIDOut
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetTaskByIDIn) dto.GetTaskByIDOut); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.GetTaskByIDOut)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetTaskByIDIn) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Remove provides a mock function with given fields: ctx, payload
func (_m *TaskUsecase) Remove(ctx context.Context, payload *dto.RemoveTaskIn) error {
	ret := _m.Called(ctx, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.RemoveTaskIn) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, payload
func (_m *TaskUsecase) Update(ctx context.Context, payload *dto.UpdateTaskIn) (dto.UpdateTaskOut, error) {
	ret := _m.Called(ctx, payload)

	var r0 dto.UpdateTaskOut
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpdateTaskIn) dto.UpdateTaskOut); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(dto.UpdateTaskOut)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.UpdateTaskIn) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTaskUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTaskUsecase(t mockConstructorTestingTNewTaskUsecase) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
