// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/edwintantawi/taskit/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ValidatorProvider is an autogenerated mock type for the ValidatorProvider type
type ValidatorProvider struct {
	mock.Mock
}

// Validate provides a mock function with given fields: validater
func (_m *ValidatorProvider) Validate(validater domain.Validater) error {
	ret := _m.Called(validater)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Validater) error); ok {
		r0 = rf(validater)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidatorProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidatorProvider creates a new instance of ValidatorProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidatorProvider(t mockConstructorTestingTNewValidatorProvider) *ValidatorProvider {
	mock := &ValidatorProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
