// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validater is an autogenerated mock type for the Validater type
type Validater struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *Validater) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidater interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidater creates a new instance of Validater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidater(t mockConstructorTestingTNewValidater) *Validater {
	mock := &Validater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
