apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  POSTGRES_PORT: NTQzMg==
  POSTGRES_DB: dGFza2l0
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: dmVyeV92ZXJ5X3NlY3VyZV9wYXNzd29yZA==
