kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: stress-test
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: api
  mode: all
  stressors:
    cpu:
      workers: 1
      load: 50
  duration: 10m
