// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/edwintantawi/taskit/internal/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, payload
func (_m *UserUsecase) Create(ctx context.Context, payload *domain.CreateUserIn) (domain.CreateUserOut, error) {
	ret := _m.Called(ctx, payload)

	var r0 domain.CreateUserOut
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateUserIn) domain.CreateUserOut); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Get(0).(domain.CreateUserOut)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateUserIn) error); ok {
		r1 = rf(ctx, payload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUsecase creates a new instance of UserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUsecase(t mockConstructorTestingTNewUserUsecase) *UserUsecase {
	mock := &UserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
