FROM node:20.9.0-alpine3.18 AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

ARG VITE_BASE_API_URL
ENV VITE_BASE_API_URL $VITE_BASE_API_URL

RUN npm run build

FROM nginx:mainline-alpine3.18-slim

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


